language: ruby
group: stable
dist: trusty
os: linux
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install autoconf automake libtool
install:
  - git clone -b master --single-branch https://github.com/obgm/libcoap.git
  - cd libcoap
  - ./autogen.sh
  - ./configure --disable-examples --disable-doxygen
  - make && sudo make install
  - cd .. && rm -rf libcoap
script:
  - ruby run_test.rb test
